apiVersion: v1
kind: Service
metadata:
  name: metaplatform-api
  namespace: metaplatform
  labels:
    app: metaplatform-api
spec:
  type: ClusterIP
  selector:
    app: metaplatform-api
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP