apiVersion: v1
kind: Service
metadata:
  name: {{ include "metaplatform.componentName" (dict "ctx" . "component" "otel-collector") }}
  labels:
    {{- include "metaplatform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "metaplatform.selectorLabels" . | nindent 4 }}
    component: otel-collector
  ports:
    {{- if .Values.receivers.otlp.grpc.enabled }}
    - name: otlp-grpc
      port: {{ .Values.receivers.otlp.grpc.port }}
      targetPort: otlp-grpc
      protocol: TCP
    {{- end }}
    {{- if .Values.receivers.otlp.http.enabled }}
    - name: otlp-http
      port: {{ .Values.receivers.otlp.http.port }}
      targetPort: otlp-http
      protocol: TCP
    {{- end }}
    {{- if .Values.receivers.prometheus.enabled }}
    - name: prometheus
      port: 8889
      targetPort: prometheus
      protocol: TCP
    {{- end }}
    {{- if .Values.extensions.healthCheck.enabled }}
    - name: health
      port: {{ .Values.extensions.healthCheck.port }}
      targetPort: health
      protocol: TCP
    {{- end }}