from pathlib import Path
import re
import json

root = Path('metaplatform-frontend/apps/web/src')
files = [p for p in root.rglob('*') if p.suffix in {'.ts', '.tsx'}]

pattern_specs = [
    ('noop onClick (empty)', r'onClick=\s*\{\s*\}'),
    ('silent catch returning mock or []', r'\.catch\([^)]*\)\s*=>\s*(?:\[\s*\]|undefined|\{\s*\}|MOCK_|mock[A-Z])'),
    ('alert/confirm/prompt', r'(?<![A-Za-z])(?:^|[^.\w])(alert|confirm|prompt)\('),
    ('window.location.reload/href', r'window\.location\.(?:reload|href\s*=)'),
    ('only-disabled button (unconditional)', r'<button[^>]*\bdisabled(?:=\{true\}|="true"|\b)(?![^>]*\{)'),
    ('empty catch block', r'catch\s*\([^)]*\)\s*\{\s*\}'),
]

compiled = []
for name, rx in pattern_specs:
    try:
        compiled.append((name, re.compile(rx)))
    except re.error as e:
        print('SKIP', name, e, flush=True)

summary = {name: 0 for name, _ in compiled}
per_file = []
for path in files:
    text = path.read_text(encoding='utf-8', errors='ignore')
    rel = path.as_posix()
    counters = {}
    for name, regex in compiled:
        m = regex.findall(text)
        counters[name] = len(m)
        summary[name] += len(m)
    if any(counters.values()):
        per_file.append({'file': rel, **counters})

out = ['# Frontend Operations Audit (2026-07-30)', '',
       'Generated by scripts/audit/operations-audit.py', '',
       '## Totals', '',
       '| Pattern | Count |',
       '|---|---:|']
for name, count in sorted(summary.items(), key=lambda kv: -kv[1]):
    out.append('| ' + name + ' | ' + str(count) + ' |')
out += ['', '## Top files by missing-operation footprint', '',
        '| File | Total |', '|---|---:|']
per_file.sort(key=lambda r: -sum(r[k] for k, _ in compiled))
for row in per_file[:40]:
    total = sum(row[k] for k, _ in compiled)
    out.append('| `' + row['file'] + '` | ' + str(total) + ' |')

Path('docs/frontend').mkdir(parents=True, exist_ok=True)
Path('docs/frontend/operations-audit-2026-07-30.md').write_text('\n'.join(out), encoding='utf-8')
Path('docs/frontend/operations-audit-2026-07-30.json').write_text(json.dumps({'totals': summary, 'files': per_file}, ensure_ascii=False, indent=2), encoding='utf-8')
print('Done', summary)
