import { useEffect, useState } from 'react';
import { Card, Col, Descriptions, Row, Space, Spin, Tag, Typography } from 'antd';
import {
  CheckCircleOutlined,
  CloseCircleOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  RobotOutlined,
} from '@ant-design/icons';
import { getReportDetail } from '@/api/evaluations';
import {
  DIMENSION_META,
  SUGGESTION_CATEGORY_META,
  SUGGESTION_PRIORITY_META,
} from '@/types';
import type { EvaluationReportDetail, OptimizationSuggestion } from '@/types';
import DimensionScoreChart from './DimensionScoreChart';

interface EvaluationReportCardProps {
  /** 基础报告或已含维度的详情；若未含 detail 字段，组件会按需自动拉取 */
  report: EvaluationReportDetail;
}

/**
 * 评估报告卡片：
 * - 基础信息（任务数 / 平均质量 / 成功率 / 平均耗时）
 * - 亮点 / 待改进
 * - 维度评分雷达图（若有 dimensions）
 * - 优化建议列表（若有 suggestions）
 * - 自动生成标识（autoGenerated）
 * - 与基线对比（comparisonBaseline，显示 delta 箭头）
 */
export default function EvaluationReportCard({ report }: EvaluationReportCardProps) {
  const [detail, setDetail] = useState<EvaluationReportDetail>(report);
  const [loading, setLoading] = useState(false);

  // 若传入的 report 不含维度/建议详情，则自动拉取一次
  useEffect(() => {
    let cancelled = false;
    const needFetch =
      !report.dimensions && !report.suggestions && !report.scoreBreakdown;
    if (!needFetch) {
      setDetail(report);
      return;
    }
    setLoading(true);
    getReportDetail(report.reportId)
      .then((d) => {
        if (!cancelled) setDetail({ ...report, ...d });
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [report]);

  const hasDimensions = (detail.dimensions?.length ?? 0) > 0;
  const hasSuggestions = (detail.suggestions?.length ?? 0) > 0;
  const baseline = detail.comparisonBaseline;

  const renderSuggestion = (s: OptimizationSuggestion) => {
    const catMeta = SUGGESTION_CATEGORY_META[s.category];
    const priMeta = SUGGESTION_PRIORITY_META[s.priority];
    return (
      <Card key={s.id} size="small" style={{ marginBottom: 8 }}>
        <Space direction="vertical" size={4} style={{ width: '100%' }}>
          <Space wrap>
            <Typography.Text strong>{s.title}</Typography.Text>
            <Tag color={catMeta.color}>{catMeta.label}</Tag>
            <Tag color={priMeta.color}>{priMeta.label}</Tag>
          </Space>
          <Typography.Text>
            <Typography.Text type="secondary">行动：</Typography.Text>
            {s.action}
          </Typography.Text>
          <Typography.Text type="success">
            预期影响：{s.expectedImpact}
          </Typography.Text>
        </Space>
      </Card>
    );
  };

  return (
    <Card
      size="small"
      title={
        <Space>
          <span>评估报告 - {detail.period}</span>
          {detail.autoGenerated && (
            <Tag color="blue" icon={<RobotOutlined />}>
              自动生成
            </Tag>
          )}
          {baseline && (
            <Tag
              color={baseline.delta >= 0 ? 'green' : 'red'}
              icon={
                baseline.delta >= 0 ? <ArrowUpOutlined /> : <ArrowDownOutlined />
              }
            >
              较上期 {baseline.delta >= 0 ? '+' : ''}
              {(baseline.delta * 100).toFixed(1)}% (基线{' '}
              {(baseline.previousScore * 100).toFixed(1)}%)
            </Tag>
          )}
        </Space>
      }
    >
      <Spin spinning={loading}>
        <Descriptions column={3} size="small">
          <Descriptions.Item label="任务总数">{detail.totalTasks}</Descriptions.Item>
          <Descriptions.Item label="平均质量">{detail.avgQualityScore.toFixed(2)}</Descriptions.Item>
          <Descriptions.Item label="成功率">{(detail.successRate * 100).toFixed(1)}%</Descriptions.Item>
          <Descriptions.Item label="平均耗时">{detail.avgDuration}s</Descriptions.Item>
        </Descriptions>

        <Row gutter={16} style={{ marginTop: 12 }}>
          <Col xs={24} md={hasDimensions ? 12 : 24}>
            <Space direction="vertical" style={{ width: '100%' }}>
              <div>
                <Typography.Text strong>亮点：</Typography.Text>
                <ul style={{ marginTop: 4 }}>
                  {detail.highlights.map((h, i) => (
                    <li key={i}>
                      <CheckCircleOutlined style={{ color: '#52c41a' }} /> {h}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <Typography.Text strong>待改进：</Typography.Text>
                <ul>
                  {detail.issues.map((it, i) => (
                    <li key={i}>
                      <CloseCircleOutlined style={{ color: '#f5222d' }} /> {it}
                    </li>
                  ))}
                </ul>
              </div>
            </Space>
          </Col>

          {hasDimensions && (
            <Col xs={24} md={12}>
              <Typography.Text strong>维度评分：</Typography.Text>
              <DimensionScoreChart dimensions={detail.dimensions!} size={280} />
              <Space wrap style={{ marginTop: 8 }}>
                {detail.dimensions!.map((d) => (
                  <Tag key={d.dimension} color={DIMENSION_META[d.dimension].color}>
                    {DIMENSION_META[d.dimension].label}: {d.score}
                  </Tag>
                ))}
              </Space>
            </Col>
          )}
        </Row>

        {hasSuggestions && (
          <div style={{ marginTop: 12 }}>
            <Typography.Text strong>优化建议：</Typography.Text>
            <div style={{ marginTop: 8 }}>
              {detail.suggestions!.map(renderSuggestion)}
            </div>
          </div>
        )}
      </Spin>
    </Card>
  );
}
