apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marketplace.fullname" . }}-worker
  labels:
    {{- include "marketplace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "marketplace.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "marketplace.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "marketplace.fullname" . }}
      containers:
        - name: marketplace-worker
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}-worker:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MATE_PROFILE
              value: production
            - name: MATE_MARKETPLACE_SAAS_URL
              value: {{ .Values.saas.baseUrl | quote }}
            - name: MATE_MARKETPLACE_REGISTRY
              value: {{ .Values.saas.registry | quote }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      restartPolicy: Always