server:
  port: 8301

spring:
  application:
    name: tech-obs
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    root: INFO
    com.metaplatform.obs: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
