apiVersion: v1
kind: Service
metadata:
  name: {{ include "datahub.fullname" . }}
  labels:
    {{- include "datahub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-gms
      port: {{ .Values.service.gms.port }}
      targetPort: http-gms
      protocol: TCP
  selector:
    {{- include "datahub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: catalog
