import { useEffect, useState } from 'react';
import {
  Button,
  Card,
  Col,
  Descriptions,
  List,
  Progress,
  Row,
  Space,
  Spin,
  Tag,
  Typography,
} from '@douyinfe/semi-ui';
import type { TagColor } from '@douyinfe/semi-ui/lib/es/tag';
import { ArrowRight, Bot, CheckCircle2, TrendingDown, TrendingUp, XCircle } from 'lucide-react';
import { getReportDetail } from '@/api/dw/evaluations';
import {
  DIMENSION_META,
  SUGGESTION_CATEGORY_META,
  SUGGESTION_PRIORITY_META,
} from '@/api/dw/types';
import type {
  DimensionScore,
  EvaluationReportDetail,
  OptimizationSuggestion,
} from '@/api/dw/types';
import { EmptyState } from '@/components/skeleton';
import '../agents.css';

interface EvaluationReportCardProps {
  /** 基础报告或已含维度的详情；若未含 detail 字段，组件会按需自动拉取 */
  report: EvaluationReportDetail;
}

/** 旧预设色名 / 16 进制色 → Semi TagColor（Semi Tag 仅支持预设色值） */
const TAG_COLOR_MAP: Record<string, TagColor> = {
  blue: 'blue',
  cyan: 'cyan',
  purple: 'purple',
  red: 'red',
  orange: 'orange',
  green: 'green',
  geekblue: 'indigo',
  magenta: 'pink',
  gold: 'yellow',
  '#1677ff': 'blue',
  '#13c2c2': 'cyan',
  '#52c41a': 'green',
  '#faad14': 'orange',
  '#f5222d': 'red',
  '#722ed1': 'purple',
};

function toTagColor(color: string): TagColor {
  return TAG_COLOR_MAP[color] ?? 'grey';
}

function scoreStrokeColor(s: number): string {
  if (s >= 85) return 'var(--semi-color-success)';
  if (s >= 70) return 'var(--semi-color-warning)';
  return 'var(--semi-color-danger)';
}

/** 维度评分条（与 AutoScorePanel 同构：标签 / Progress / 分值，无手绘 SVG）。 */
function DimensionBars({ dimensions }: { dimensions: DimensionScore[] }) {
  return (
    <Row gutter={[12, 16]}>
      {dimensions.map((d) => {
        // 后端可能返回前端未登记的维度枚举，统一兜底
        const meta = DIMENSION_META[d.dimension];
        const label = meta?.label ?? d.dimension;
        return (
          <Col span={24} key={d.dimension}>
            <Row gutter={12} type="flex" align="middle">
              <Col span={7}>
                <Typography.Text>{label}</Typography.Text>
              </Col>
              <Col span={13}>
                <Progress
                  percent={d.score}
                  stroke={scoreStrokeColor(d.score)}
                  showInfo={false}
                  aria-label={`${label} ${d.score} 分`}
                />
              </Col>
              <Col span={4}>
                <Tag color={toTagColor(meta?.color ?? 'grey')}>{d.score}</Tag>
              </Col>
            </Row>
          </Col>
        );
      })}
    </Row>
  );
}

/**
 * 评估报告卡片：
 * - 基础信息（任务数 / 平均质量 / 成功率 / 平均耗时）
 * - 亮点 / 待改进
 * - 维度评分条
 * - 优化建议列表
 * - 自动生成标识与基线对比
 */
export default function EvaluationReportCard({ report }: EvaluationReportCardProps) {
  const [detail, setDetail] = useState<EvaluationReportDetail>(report);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // 若传入的 report 不含维度/建议详情，则自动拉取一次
  useEffect(() => {
    let cancelled = false;
    const needFetch = !report.dimensions && !report.suggestions && !report.scoreBreakdown;
    if (!needFetch) {
      setDetail(report);
      setError('');
      return;
    }
    setLoading(true);
    setError('');
    getReportDetail(report.reportId)
      .then((d) => {
        if (!cancelled) setDetail({ ...report, ...d });
      })
      .catch((e) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [report]);

  const hasDimensions = (detail.dimensions?.length ?? 0) > 0;
  const hasSuggestions = (detail.suggestions?.length ?? 0) > 0;
  const baseline = detail.comparisonBaseline;

  const renderSuggestion = (s: OptimizationSuggestion) => {
    // 后端可能返回前端未登记的枚举值，统一兜底
    const catMeta = SUGGESTION_CATEGORY_META[s.category];
    const priMeta = SUGGESTION_PRIORITY_META[s.priority];
    return (
      <Card
        key={s.id}
        title={
          <span className="mp-agent-line">
            <Typography.Text strong>{s.title}</Typography.Text>
            <span className="mp-agent-chips">
              <Tag color={toTagColor(catMeta?.color ?? 'grey')} type="light">
                {catMeta?.label ?? s.category}
              </Tag>
              <Tag color={toTagColor(priMeta?.color ?? 'grey')} type="light">
                {priMeta?.label ?? s.priority}
              </Tag>
            </span>
          </span>
        }
      >
        <Typography.Paragraph>{s.action}</Typography.Paragraph>
        <Typography.Text type="success">
          <ArrowRight size={13} strokeWidth={1.5} /> 预期影响：{s.expectedImpact}
        </Typography.Text>
      </Card>
    );
  };

  return (
    <Card
      title={
        <Space wrap>
          <span>评估报告 · {detail.period}</span>
          {detail.autoGenerated ? (
            <Tag color="blue" type="light">
              <Bot size={12} strokeWidth={1.5} /> 自动生成
            </Tag>
          ) : null}
          {baseline ? (
            <Tag color={baseline.delta >= 0 ? 'green' : 'red'} type="light">
              {baseline.delta >= 0 ? (
                <TrendingUp size={12} strokeWidth={1.5} />
              ) : (
                <TrendingDown size={12} strokeWidth={1.5} />
              )}{' '}
              较上期 {baseline.delta >= 0 ? '+' : ''}
              {(baseline.delta * 100).toFixed(1)}%（基线 {(baseline.previousScore * 100).toFixed(1)}%）
            </Tag>
          ) : null}
        </Space>
      }
    >
      {error ? (
        <EmptyState illustration="failure" title="报告详情加载失败" desc={error} />
      ) : (
        <Spin spinning={loading}>
          <Descriptions
            row
            data={[
              { key: '任务总数', value: String(detail.totalTasks) },
              { key: '平均质量', value: detail.avgQualityScore.toFixed(2) },
              { key: '成功率', value: `${(detail.successRate * 100).toFixed(1)}%` },
              { key: '平均耗时', value: `${detail.avgDuration}s` },
            ]}
          />

          <Row gutter={[16, 16]}>
            <Col xs={24} md={hasDimensions ? 12 : 24}>
              <Card title="亮点 / 待改进">
                <Typography.Text type="tertiary" size="small">
                  亮点
                </Typography.Text>
                {detail.highlights.length === 0 ? (
                  <Typography.Paragraph type="tertiary">暂无亮点记录</Typography.Paragraph>
                ) : (
                  <List
                    split={false}
                    dataSource={detail.highlights}
                    renderItem={(h: string, i: number) => (
                      <List.Item
                        key={i}
                        main={
                          <span className="mp-agent-line">
                            <span className="mp-agent-chips">
                              <CheckCircle2
                                size={14}
                                strokeWidth={1.5}
                                color="var(--semi-color-success)"
                              />
                              {h}
                            </span>
                          </span>
                        }
                      />
                    )}
                  />
                )}

                <Typography.Text type="tertiary" size="small">
                  待改进
                </Typography.Text>
                {detail.issues.length === 0 ? (
                  <Typography.Paragraph type="tertiary">暂无待改进项</Typography.Paragraph>
                ) : (
                  <List
                    split={false}
                    dataSource={detail.issues}
                    renderItem={(it: string, i: number) => (
                      <List.Item
                        key={i}
                        main={
                          <span className="mp-agent-line">
                            <span className="mp-agent-chips">
                              <XCircle
                                size={14}
                                strokeWidth={1.5}
                                color="var(--semi-color-danger)"
                              />
                              {it}
                            </span>
                          </span>
                        }
                      />
                    )}
                  />
                )}
              </Card>
            </Col>

            {hasDimensions ? (
              <Col xs={24} md={12}>
                <Card title="维度评分">
                  <DimensionBars dimensions={detail.dimensions ?? []} />
                </Card>
              </Col>
            ) : null}
          </Row>

          {hasSuggestions ? (
            <Row gutter={[16, 16]}>
              {detail.suggestions?.map((s) => (
                <Col span={24} key={s.id}>
                  {renderSuggestion(s)}
                </Col>
              ))}
            </Row>
          ) : null}
        </Spin>
      )}
    </Card>
  );
}
