import '@testing-library/jest-dom/vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { MemoryRouter } from 'react-router-dom';
import AppListPage from './AppListPage';
import * as api from '@/api/apphub/apps';
vi.hoisted(() => { HTMLCanvasElement.prototype.getContext = (() => ({ fillRect() {}, clearRect() {}, getImageData: () => ({ data: new Uint8ClampedArray(4) }) })) as never; });
vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} });
Range.prototype.getBoundingClientRect = () => new DOMRect();
vi.mock('@/contexts/SettingsContext', () => ({ useSettings: () => ({ resolvedTheme: 'light' }) }));
vi.mock('./DesignFlowPage', () => ({ default: () => null }));
vi.mock('./components/DomainManageDrawer', () => ({ default: () => null }));
vi.mock('@/api/apphub/apps', () => ({ listApps: vi.fn(), listGroups: vi.fn(), listDomains: vi.fn(), deleteApp: vi.fn() }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
it('retains apps and retries classifications independently instead of verifying an empty classification', async () => {
  vi.mocked(api.listApps).mockResolvedValue({ items: [{ appId: 'app-1', name: '实际应用', code: 'actual', description: '实际描述', updatedAt: '1.0' }] } as never);
  vi.mocked(api.listGroups).mockRejectedValueOnce(new Error('分类不可用')).mockResolvedValueOnce(['business']);
  vi.mocked(api.listDomains).mockRejectedValueOnce(new Error('业务域不可用')).mockResolvedValueOnce([]);
  render(<MemoryRouter><AppListPage /></MemoryRouter>);
  expect(await screen.findByText('分类不可用')).toBeVisible();
  expect(screen.getByText('实际应用')).toBeVisible();
  fireEvent.click(screen.getByRole('button', { name: '重试分类' }));
  fireEvent.click(screen.getByRole('button', { name: '重试业务域' }));
  await screen.findByText('全部分类');
  expect(api.listApps).toHaveBeenCalledTimes(1);
  expect(api.listGroups).toHaveBeenCalledTimes(2);
  expect(api.listDomains).toHaveBeenCalledTimes(2);
});
