server:
  port: 8106

spring:
  application:
    name: tech-ea
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

ea:
  ont:
    base-url: ${ONT_BASE_URL:http://localhost:8201}
