package com.metaplatform.appservice.domain.dynamic;

import com.metaplatform.appservice.api.error.ApiException;
import com.metaplatform.appservice.domain.object.AppObjectService;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.security.MessageDigest;
import java.util.List;
import java.util.regex.Pattern;

/**
 * 动态业务数据表 —— 在该服务里管理运行时创建的物理表（data_{app}_{obj}_{hash}）。
 *
 * <p>归属 Sprint 0 ARCHITECTURE_NOTE：
 *  ontology-engine 仅提供 ObjectType 语义层，DDL 由 app-service 自己持有。
 */
@Service
public class DynamicTableService {

    private static final Pattern IDENT_PATTERN = Pattern.compile("^[a-z][a-z0-9_]{0,62}$");

    @PersistenceContext
    private EntityManager em;

    /**
     * 给新建对象创建物理数据表。
     * @return 物理表名（格式 data_{code}_{hash}）
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public String createTable(String objectCode, List<AppObjectService.FieldDef> fields) {
        if (!IDENT_PATTERN.matcher(objectCode).matches()) {
            throw ApiException.badRequest("非法 objectCode");
        }
        String hash = shortHash(objectCode + System.nanoTime());
        String tableName = "data_" + objectCode + "_" + hash;

        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ").append(tableName).append(" (");
        sql.append("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ");
        sql.append("tenant_id VARCHAR(64) NOT NULL, ");
        sql.append("created_by VARCHAR(64) NOT NULL, ");
        sql.append("created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ");
        sql.append("updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP");

        for (var f : fields) {
            if (!IDENT_PATTERN.matcher(f.code()).matches()) {
                throw ApiException.badRequest("非法字段 code: " + f.code());
            }
            sql.append(", ").append(f.code()).append(" ");
            switch (f.type()) {
                case "number" -> sql.append("DOUBLE PRECISION");
                case "boolean" -> sql.append("BOOLEAN");
                case "date" -> sql.append("DATE");
                case "datetime" -> sql.append("TIMESTAMP");
                default -> sql.append("TEXT");
            }
            if (Boolean.TRUE.equals(f.required())) {
                sql.append(" NOT NULL");
            }
        }
        sql.append(")");

        em.createNativeQuery(sql.toString()).executeUpdate();
        em.createNativeQuery("CREATE INDEX idx_" + tableName + "_tenant ON " + tableName + "(tenant_id)")
                .executeUpdate();
        return tableName;
    }

    @Transactional(propagation = Propagation.MANDATORY)
    public void dropTable(String tableName) {
        if (!tableName.matches("^data_[a-z][a-z0-9_]+$")) {
            throw ApiException.badRequest("非法表名");
        }
        em.createNativeQuery("DROP TABLE IF EXISTS " + tableName).executeUpdate();
    }

    private static String shortHash(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            byte[] b = md.digest(input.getBytes());
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 4; i++) sb.append(String.format("%02x", b[i]));
            return sb.toString();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
