package com.metaplatform.appservice.domain.dynamic;

import com.metaplatform.appservice.api.error.ApiException;
import com.metaplatform.appservice.domain.object.AppObjectService;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.security.MessageDigest;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Pattern;

/**
 * 动态业务数据表 —— 在该服务里管理运行时创建的物理表（data_{app}_{obj}_{hash}）。
 *
 * <p>归属 Sprint 0 ARCHITECTURE_NOTE：
 *  ontology-engine 仅提供 ObjectType 语义层，DDL 由 app-service 自己持有。
 */
@Service
public class DynamicTableService {

    private static final Pattern IDENT_PATTERN = Pattern.compile("^[a-z][a-z0-9_]{0,62}$");
    private static final Pattern TABLE_NAME_PATTERN = Pattern.compile("^data_[a-z][a-z0-9_]+$");

    @PersistenceContext
    private EntityManager em;

    private final JdbcTemplate jdbcTemplate;

    public DynamicTableService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * 给新建对象创建物理数据表。允许空字段列表，仅创建基础元数据列。
     * @return 物理表名（格式 data_{code}_{hash}）
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public String createTable(String objectCode, List<AppObjectService.FieldDef> fields) {
        if (!IDENT_PATTERN.matcher(objectCode).matches()) {
            throw ApiException.badRequest("非法 objectCode");
        }
        String hash = shortHash(objectCode + System.nanoTime());
        String tableName = "data_" + objectCode + "_" + hash;

        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ").append(tableName).append(" (");
        sql.append("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ");
        sql.append("tenant_id VARCHAR(64) NOT NULL, ");
        sql.append("created_by VARCHAR(64) NOT NULL, ");
        sql.append("created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ");
        sql.append("updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP");

        if (fields != null) {
            for (var f : fields) {
                appendColumn(sql, f);
            }
        }
        sql.append(")");

        em.createNativeQuery(sql.toString()).executeUpdate();
        em.createNativeQuery("CREATE INDEX idx_" + tableName + "_tenant ON " + tableName + "(tenant_id)")
                .executeUpdate();
        return tableName;
    }

    /**
     * 向已有物理表追加一列。
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public void addColumn(String tableName, AppObjectService.FieldDef field) {
        if (!TABLE_NAME_PATTERN.matcher(tableName).matches()) {
            throw ApiException.badRequest("非法表名: " + tableName);
        }
        if (!IDENT_PATTERN.matcher(field.code()).matches()) {
            throw ApiException.badRequest("非法字段 code: " + field.code());
        }
        StringBuilder sql = new StringBuilder();
        sql.append("ALTER TABLE ").append(tableName).append(" ADD COLUMN ");
        appendColumnDef(sql, field);
        em.createNativeQuery(sql.toString()).executeUpdate();
    }

    @Transactional(propagation = Propagation.MANDATORY)
    public void dropTable(String tableName) {
        if (!TABLE_NAME_PATTERN.matcher(tableName).matches()) {
            throw ApiException.badRequest("非法表名");
        }
        em.createNativeQuery("DROP TABLE IF EXISTS " + tableName).executeUpdate();
    }

    /**
     * 向动态业务表插入一行记录，返回自增 id。
     *
     * <p>row 中的 key 必须已作为列存在；未在 row 中出现的列留空。
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public Long insertRow(String tableName, Map<String, Object> row, String tenantId, String createdBy) {
        if (!TABLE_NAME_PATTERN.matcher(tableName).matches()) {
            throw ApiException.badRequest("非法表名: " + tableName);
        }
        if (tenantId == null || tenantId.isBlank()) {
            throw ApiException.badRequest("tenantId 不能为空");
        }

        List<String> columns = new ArrayList<>(List.of("tenant_id", "created_by"));
        List<Object> values = new ArrayList<>(List.of(tenantId, createdBy));
        for (var entry : row.entrySet()) {
            String col = entry.getKey();
            if (!IDENT_PATTERN.matcher(col).matches()) {
                throw ApiException.badRequest("非法字段名: " + col);
            }
            columns.add(col);
            values.add(entry.getValue());
        }

        String colSql = String.join(", ", columns);
        String placeholders = String.join(", ", columns.stream().map(c -> "?").toList());
        String sql = "INSERT INTO " + tableName + " (" + colSql + ") VALUES (" + placeholders + ")";

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(sql, new String[]{"id"});
            for (int i = 0; i < values.size(); i++) {
                ps.setObject(i + 1, values.get(i));
            }
            return ps;
        }, keyHolder);

        Optional<Number> key = Optional.ofNullable(keyHolder.getKey());
        return key.map(Number::longValue)
                .orElseThrow(() -> ApiException.internalError("插入后未能获取自增主键"));
    }

    /**
     * 校验指定列值在当前租户下是否已存在（唯一性校验）。
     */
    @Transactional(propagation = Propagation.MANDATORY)
    public boolean exists(String tableName, String column, Object value, String tenantId) {
        if (!TABLE_NAME_PATTERN.matcher(tableName).matches()) {
            throw ApiException.badRequest("非法表名: " + tableName);
        }
        if (!IDENT_PATTERN.matcher(column).matches()) {
            throw ApiException.badRequest("非法字段名: " + column);
        }
        String sql = "SELECT COUNT(*) FROM " + tableName + " WHERE tenant_id = ? AND " + column + " = ?";
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, tenantId, value);
        return count != null && count > 0;
    }

    private void appendColumn(StringBuilder sql, AppObjectService.FieldDef f) {
        sql.append(", ");
        appendColumnDef(sql, f);
    }

    private void appendColumnDef(StringBuilder sql, AppObjectService.FieldDef f) {
        sql.append(f.code()).append(" ");
        switch (f.type()) {
            case "number" -> sql.append("DOUBLE PRECISION");
            case "boolean" -> sql.append("BOOLEAN");
            case "date" -> sql.append("DATE");
            case "datetime" -> sql.append("TIMESTAMP");
            default -> sql.append("TEXT");
        }
        if (Boolean.TRUE.equals(f.required())) {
            sql.append(" NOT NULL");
        }
    }

    private static String shortHash(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            byte[] b = md.digest(input.getBytes());
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 4; i++) sb.append(String.format("%02x", b[i]));
            return sb.toString();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
