"""marketplace error codes(SPEC §4.1)。"""

from __future__ import annotations

from enum import Enum


class MPErrorCode(str, Enum):
    DIGEST_MISMATCH = "MP_DIGEST_MISMATCH"
    MANIFEST_INVALID = "MP_MANIFEST_INVALID"
    LICENSE_INVALID = "MP_LICENSE_INVALID"
    LICENSE_EXPIRED = "MP_LICENSE_EXPIRED"
    LICENSE_QUOTA_EXCEEDED = "MP_LICENSE_QUOTA_EXCEEDED"
    INCOMPATIBLE_PLATFORM = "MP_INCOMPATIBLE_PLATFORM"
    KIND_NOT_ALLOWED = "MP_KIND_NOT_ALLOWED"
    SAAS_UNREACHABLE = "MP_SAAS_UNREACHABLE"
    INTERNAL = "MP_INTERNAL"