version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mp-base-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: platform_base
      POSTGRES_USER: base
      POSTGRES_PASSWORD: metaplatform
    volumes:
      - pg-base-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mp-base-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-base-data:/data

  kafka:
    image: apache/kafka:3.6.1
    container_name: mp-base-kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

volumes:
  pg-base-data:
  redis-base-data:
