"""G6 OSDK typed client 生成器：从 OpenAPI 契约（services/*.yaml）生成
Python typed client（每个 operationId 一个方法）。

用法::

    python scripts/generate_typed_client.py \\
        contracts/openapi/services/ont.yaml \\
        packages/mate-clients/src/mate_clients/osdk_generated.py

生成物为确定性代码（同契约 → 同输出）；路径参数成为方法位置参数，
query/body 以 kwargs 透传。鉴权/租户头由 GeneratedClient 基类注入
（复用 OntologySDK 同款 GOVERN-06 双头语义）。
"""
from __future__ import annotations

import sys

import yaml

HEADER = '''"""AUTO-GENERATED by scripts/generate_typed_client.py — DO NOT EDIT.

Source contract: {source}
Operations: {count}
"""
from __future__ import annotations

from typing import Any

import httpx


class GeneratedClient:
    """Typed client with one method per contract operationId."""

    def __init__(self, base_url: str = "http://localhost:8100",
                 token: str = "", tenant_id: str = "tenant-default",
                 *, timeout: float = 60.0) -> None:
        self._base = base_url.rstrip("/")
        self._client = httpx.Client(
            timeout=timeout,
            headers={{"X-Tenant-Id": tenant_id,
                      "Authorization": f"Bearer {{token}}"}} if token
            else {{"X-Tenant-Id": tenant_id}},
        )

    def _request(self, method: str, path: str, **kwargs: Any) -> Any:
        resp = self._client.request(method, f"{{self._base}}{{path}}", **kwargs)
        if resp.status_code >= 300:
            raise RuntimeError(f"{{resp.status_code}}: {{resp.text[:300]}}")
        return resp.json() if resp.content else {{}}
'''

METHOD = '''
    def {name}(self{params}) -> Any:
        """{summary}"""
        path = {path_expr}
        return self._request("{method}", path{kw_expr})
'''


def sanitize(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isalnum() or ch == "_":
            out.append(ch.lower())
        else:
            out.append("_" if i else "_")
    return "".join(out)


def generate(contract_path: str) -> str:
    spec = yaml.safe_load(open(contract_path, encoding="utf-8"))
    src = contract_path.replace("\\", "/").split("/")[-1]
    methods: list[str] = []
    count = 0
    for path, item in sorted((spec.get("paths") or {}).items()):
        for method, op in item.items():
            if method not in ("get", "post", "put", "delete", "patch"):
                continue
            op_id = op.get("operationId")
            if not op_id:
                continue
            count += 1
            name = sanitize(op_id)
            params = []
            path_params = [p for p in (op.get("parameters") or [])
                           if isinstance(p, dict) and p.get("in") == "path"]
            for p in path_params:
                params.append(f", {sanitize(p['name'])}: str")
            # path 表达式：f-string 替换 {param}
            path_expr = 'f"' + path.replace("{", "{").replace("}", "}") + '"'
            for p in path_params:
                pn = sanitize(p["name"])
                path_expr = path_expr.replace("{" + p["name"] + "}", "{" + pn + "}")
            has_body = method in ("post", "put", "patch")
            kw = ""
            if has_body:
                params.append(", **body: Any")
                kw = ", json=body"
            else:
                params.append(", **params: Any")
                kw = ", params=params"
            summary = (op.get("summary") or op.get("description") or op_id)
            summary = str(summary).split("\n")[0][:110]
            methods.append(METHOD.format(
                name=name, params="".join(params), summary=summary,
                path_expr=path_expr, method=method.upper(), kw_expr=kw))
    return HEADER.format(source=src, count=count) + "\n" + "\n".join(methods)


def _cli() -> int:
    import argparse

    ap = argparse.ArgumentParser(
        prog="generate_typed_client",
        description="Generate a typed Python client from an OpenAPI contract.")
    ap.add_argument("contract", help="path to services/*.yaml")
    ap.add_argument("-o", "--out", required=True, help="output .py path")
    args = ap.parse_args()
    code = generate(args.contract)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(code)
    n = code.count("    def ")
    print(f"generated {args.out} from {args.contract} ({n} operations)")
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
