"""KERNEL-01 service-level Protocol —— runtime 可独立实现。

12 基元的 CRUD / query / apply Protocol。FastAPI 适配层（mate-tech-ont-v2）和其他
runtime（CLI / SDK / sandbox executor）共享同一抽象。
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable, Protocol, runtime_checkable

from ..ontology.identity import ClassRef, Version
from ..ontology.instances import Individual, LinkInstance
from ..ontology.query import ObjectSet
from ..ontology.reasoning import Axiom, Function
from ..ontology.types import (
    ActionType,
    Cardinality,
    Directionality,
    Interface,
    LinkType,
    ObjectType,
    Property,
    PropertyFormat,
)


@runtime_checkable
class OntologyRepository(Protocol):
    """12 基元的存储抽象（runtime 决定落盘 / in-memory / DB）。"""

    # ───── identity ─────
    def resolve_class_ref(self, rid: str) -> ClassRef: ...
    def snapshot_version(self, class_rid: ClassRef, author: str, parent: str | None, change_set: tuple[str, ...]) -> Version: ...
    def list_versions(self, class_rid: ClassRef) -> list[Version]: ...

    # ───── types ─────
    def upsert_property(self, p: Property) -> Property: ...
    def upsert_object_type(self, ot: ObjectType) -> ObjectType: ...
    def upsert_link_type(self, lt: LinkType) -> LinkType: ...
    def upsert_action_type(self, at: ActionType) -> ActionType: ...
    def upsert_interface(self, i: Interface) -> Interface: ...
    def list_object_types(self, limit: int, offset: int) -> list[ObjectType]: ...
    def list_link_types(self) -> list[LinkType]: ...
    def list_action_types(self) -> list[ActionType]: ...
    def list_interfaces(self) -> list[Interface]: ...
    def get_object_type(self, rid: ClassRef) -> ObjectType: ...
    def get_link_type(self, rid: ClassRef) -> LinkType: ...
    def get_action_type(self, rid: ClassRef) -> ActionType: ...

    # ───── instances ─────
    def create_individual(self, ind: Individual) -> Individual: ...
    def get_individual(self, rid: str) -> Individual: ...
    def list_individuals(self, class_rid: ClassRef | None) -> list[Individual]: ...
    def create_link_instance(self, li: LinkInstance) -> LinkInstance: ...
    def list_link_instances(self) -> list[LinkInstance]: ...

    # ───── reasoning ─────
    def upsert_axiom(self, ax: Axiom) -> Axiom: ...
    def list_axioms(self) -> list[Axiom]: ...
    def upsert_function(self, f: Function) -> Function: ...
    def list_functions(self) -> list[Function]: ...

    # ───── query / apply ─────
    def evaluate_object_set(self, os_: ObjectSet) -> list[Individual]: ...
    def apply_action(self, action_rid: ClassRef, target_iid: str, parameters: dict[str, Any], provenance: dict[str, Any]) -> tuple[datetime, list[str]]: ...


__all__ = ["OntologyRepository"]