spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metaplatform_rag
    username: meta
    password: meta
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  config:
    import: []
  autoconfigure:
    exclude:
      - org.springframework.cloud.context.refresh.ContextRefresherAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.cloud.autoconfigure.RefreshAutoConfiguration
      - com.alibaba.cloud.nacos.registry.NacosServiceRegistryAutoConfiguration
      - org.springframework.ai.mcp.server.common.autoconfigure.annotations.McpServerSpecificationFactoryAutoConfiguration
      - org.springframework.ai.vectorstore.milvus.autoconfigure.MilvusVectorStoreAutoConfiguration
      - org.springframework.ai.mcp.client.autoconfigure.McpClientAutoConfiguration
      - com.alibaba.cloud.ai.agent.nacos.config.NacosAgentConfig
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - com.alibaba.cloud.nacos.discovery.NacosDiscoveryAutoConfiguration
      - com.alibaba.cloud.nacos.NacosConfigAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.nacosconfig.NacosConfigAutoConfiguration
      - org.springframework.ai.mcp.server.common.autoconfigure.annotations.McpServerAnnotationScannerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.nacos.NacosMcServerAutoConfiguration
      - org.springframework.ai.mcp.server.common.autoconfigure.McpServerAutoConfiguration
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-placeholder-for-dev-only-not-real}

logging:
  level:
    com.metaplatform.rag: DEBUG
