/**
 * MSW codegen script (ST-6.5.2).
 *
 * Usage: tsx scripts/msw-codegen.ts <openapi.yaml>
 */
import { readFileSync, writeFileSync } from "node:fs";

interface OpenAPISpec {
  paths: Record<string, Record<string, unknown>>;
}

function genHandler(method: string, path: string): string {
  return `  http.${method.toLowerCase()}("${path}", async () => {
    return HttpResponse.json({ mock: true, path: "${path}" });
  }),`;
}

function parseSimpleYaml(text: string): OpenAPISpec {
  const paths: Record<string, Record<string, unknown>> = {};
  const lines = text.split("\n");
  let current_path: string | null = null;
  for (const line of lines) {
    const pathMatch = line.match(/^  (\/[^:]+):$/);
    if (pathMatch) {
      current_path = pathMatch[1];
      paths[current_path] = {};
    } else if (current_path) {
      const methodMatch = line.match(/^    (get|post|put|delete|patch):/);
      if (methodMatch) {
        paths[current_path][methodMatch[1]] = {};
      }
    }
  }
  return { paths };
}

function main() {
  const specPath = process.argv[2];
  if (!specPath) {
    console.error("Usage: tsx msw-codegen.ts <openapi.yaml>");
    process.exit(1);
  }

  const raw = readFileSync(specPath, "utf-8");
  const spec = parseSimpleYaml(raw);

  const handlers: string[] = [];
  handlers.push("// Auto-generated by msw-codegen.ts");
  handlers.push('import { http, HttpResponse } from "msw";');
  handlers.push("");
  handlers.push("export const handlers = [");
  for (const [path, methods] of Object.entries(spec.paths ?? {})) {
    for (const method of Object.keys(methods)) {
      if (["get", "post", "put", "delete", "patch"].includes(method.toLowerCase())) {
        handlers.push(genHandler(method, path));
      }
    }
  }
  handlers.push("];");

  const out = handlers.join("\n");
  if (process.argv[3] === "-o") {
    writeFileSync(process.argv[4] ?? "handlers.ts", out);
  } else {
    console.log(out);
  }
}

main();